using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace IntegratedModManager.Core;

public sealed record PersistentVariableValue(string Name, string Value);

public static class ThreeDmigotoPersistentState
{
    public const string BridgeMarker = "; Generated by Integrated Mod Manager - temporary persistent-state bridge";
    private static readonly Regex SectionPattern = new(@"^\[(?<section>[^\]]+)\]\s*$", RegexOptions.CultureInvariant);
    private static readonly Regex NamespacePattern = new(@"^namespace\s*=\s*(?<namespace>.+?)\s*$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    private static readonly Regex PersistentDeclarationPattern = new(@"^global\s+persist\s+(?<name>\$[^\s=]+)(?:\s*=.*)?$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    private static readonly Regex AssignmentPattern = new(@"^(?<name>\$.+?)\s*=\s*(?<value>.+?)\s*$", RegexOptions.CultureInvariant);
    private static readonly Regex ValidVariableNamePattern = new(@"^\$(?:\\[^\\=;\[\]\r\n]+)+$|^\$[^\\\s=;\[\]]+$", RegexOptions.CultureInvariant);
    private static readonly Regex NumericValuePattern = new(@"^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$", RegexOptions.CultureInvariant);

    public static IReadOnlyDictionary<string, string> ParseUserConfig(string content)
    {
        ArgumentNullException.ThrowIfNull(content);

        var values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        bool inConstants = false;
        foreach (string rawLine in EnumerateLines(content))
        {
            string line = rawLine.Trim();
            if (line.Length == 0 || line.StartsWith(';'))
            {
                continue;
            }

            if (TryReadSection(line, out string? section))
            {
                inConstants = section.Equals("Constants", StringComparison.OrdinalIgnoreCase);
                continue;
            }

            if (!inConstants)
            {
                continue;
            }

            Match match = AssignmentPattern.Match(line);
            if (!match.Success)
            {
                continue;
            }

            string name = NormalizeVariableName(match.Groups["name"].Value);
            string value = match.Groups["value"].Value.Trim();
            if (IsSupportedNumericValue(value))
            {
                values[name] = value;
            }
        }

        return values;
    }

    public static IReadOnlySet<string> ParsePersistentVariableNames(string content, string defaultNamespace)
    {
        ArgumentNullException.ThrowIfNull(content);
        ArgumentException.ThrowIfNullOrWhiteSpace(defaultNamespace);

        string effectiveNamespace = NormalizeNamespace(defaultNamespace);
        bool reachedFirstSection = false;
        bool inConstants = false;
        var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (string rawLine in EnumerateLines(content))
        {
            string line = rawLine.Trim();
            if (line.Length == 0 || line.StartsWith(';'))
            {
                continue;
            }

            if (TryReadSection(line, out string? section))
            {
                reachedFirstSection = true;
                inConstants = section.Equals("Constants", StringComparison.OrdinalIgnoreCase);
                continue;
            }

            if (!reachedFirstSection)
            {
                Match namespaceMatch = NamespacePattern.Match(line);
                if (namespaceMatch.Success)
                {
                    effectiveNamespace = NormalizeNamespace(namespaceMatch.Groups["namespace"].Value);
                }

                continue;
            }

            if (!inConstants)
            {
                continue;
            }

            Match declaration = PersistentDeclarationPattern.Match(line);
            if (!declaration.Success)
            {
                continue;
            }

            string declaredName = declaration.Groups["name"].Value;
            names.Add(QualifyVariableName(declaredName, effectiveNamespace));
        }

        return names;
    }

    public static IReadOnlyList<PersistentVariableValue> CaptureModState(
        string modsRoot,
        string modDirectory,
        string userConfigContent)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(modsRoot);
        ArgumentException.ThrowIfNullOrWhiteSpace(modDirectory);
        ArgumentNullException.ThrowIfNull(userConfigContent);

        string fullRoot = Path.GetFullPath(modsRoot).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        string fullMod = Path.GetFullPath(modDirectory).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        if (!IsPathInside(fullMod, fullRoot) || !Directory.Exists(fullMod))
        {
            throw new ArgumentException("The Mod directory must exist inside the Mods root.", nameof(modDirectory));
        }

        IReadOnlyDictionary<string, string> userValues = ParseUserConfig(userConfigContent);
        var declaredNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (string iniPath in Directory.EnumerateFiles(fullMod, "*.ini", SearchOption.AllDirectories))
        {
            string relativeIniPath = Path.GetRelativePath(fullRoot, iniPath)
                .Replace(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar);
            string defaultNamespace = $"Mods\\{relativeIniPath}";
            string iniContent = File.ReadAllText(iniPath);
            declaredNames.UnionWith(ParsePersistentVariableNames(iniContent, defaultNamespace));
        }

        return declaredNames
            .Where(userValues.ContainsKey)
            .Select(name => new PersistentVariableValue(name, userValues[name]))
            .OrderBy(entry => entry.Name, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    public static string BuildBridge(IEnumerable<PersistentVariableValue> variables)
    {
        List<PersistentVariableValue> normalized = NormalizeVariables(variables);

        var builder = new StringBuilder();
        builder.AppendLine(BridgeMarker);
        builder.AppendLine("; Loaded for one reload, then removed before the state is persisted.");
        builder.AppendLine();
        builder.AppendLine("[Constants]");
        foreach (PersistentVariableValue entry in normalized)
        {
            builder.Append("post ").Append(entry.Name).Append(" = ").AppendLine(entry.Value);
        }

        return builder.ToString();
    }

    public static string MergeUserConfig(string content, IEnumerable<PersistentVariableValue> variables)
    {
        ArgumentNullException.ThrowIfNull(content);
        List<PersistentVariableValue> normalized = NormalizeVariables(variables);
        var targetValues = normalized.ToDictionary(entry => entry.Name, entry => entry.Value, StringComparer.OrdinalIgnoreCase);
        var pending = normalized.ToDictionary(entry => entry.Name, entry => entry.Value, StringComparer.OrdinalIgnoreCase);
        string newline = content.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";
        List<string> lines = EnumerateLines(content).ToList();
        bool hadTerminalNewline = content.EndsWith("\n", StringComparison.Ordinal);
        int constantsStart = -1;
        int constantsEnd = lines.Count;

        for (int index = 0; index < lines.Count; index++)
        {
            string trimmed = lines[index].Trim();
            if (!TryReadSection(trimmed, out string section))
            {
                continue;
            }

            if (constantsStart < 0 && section.Equals("Constants", StringComparison.OrdinalIgnoreCase))
            {
                constantsStart = index;
                continue;
            }

            if (constantsStart >= 0)
            {
                constantsEnd = index;
                break;
            }
        }

        if (constantsStart < 0)
        {
            if (lines.Count > 0 && lines[^1].Length > 0)
            {
                lines.Add(string.Empty);
            }

            lines.Add("[Constants]");
            lines.AddRange(normalized.Select(entry => $"{entry.Name} = {entry.Value}"));
            return string.Join(newline, lines) + newline;
        }

        for (int index = constantsStart + 1; index < constantsEnd; index++)
        {
            Match assignment = AssignmentPattern.Match(lines[index].Trim());
            if (!assignment.Success)
            {
                continue;
            }

            string name;
            try
            {
                name = NormalizeVariableName(assignment.Groups["name"].Value);
            }
            catch (InvalidDataException)
            {
                continue;
            }

            if (targetValues.TryGetValue(name, out string? value))
            {
                lines[index] = $"{name} = {value}";
                pending.Remove(name);
            }
        }

        if (pending.Count > 0)
        {
            lines.InsertRange(constantsEnd, pending
                .OrderBy(pair => pair.Key, StringComparer.OrdinalIgnoreCase)
                .Select(pair => $"{pair.Key} = {pair.Value}"));
        }

        string merged = string.Join(newline, lines);
        return hadTerminalNewline ? merged + newline : merged;
    }

    public static bool IsGeneratedBridge(string content)
    {
        return content?.StartsWith(BridgeMarker, StringComparison.Ordinal) == true;
    }

    private static List<PersistentVariableValue> NormalizeVariables(IEnumerable<PersistentVariableValue> variables)
    {
        ArgumentNullException.ThrowIfNull(variables);

        List<PersistentVariableValue> normalized = variables
            .Select(entry =>
            {
                ArgumentNullException.ThrowIfNull(entry);
                string name = NormalizeVariableName(entry.Name);
                string value = entry.Value.Trim();
                if (!IsSupportedNumericValue(value))
                {
                    throw new InvalidDataException($"Unsupported persistent value for {name}.");
                }

                return new PersistentVariableValue(name, value);
            })
            .GroupBy(entry => entry.Name, StringComparer.OrdinalIgnoreCase)
            .Select(group => group.Last())
            .OrderBy(entry => entry.Name, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (normalized.Count == 0)
        {
            throw new InvalidDataException("The state preset contains no persistent variables.");
        }

        return normalized;
    }

    private static bool IsPathInside(string candidate, string root)
    {
        return candidate.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase);
    }

    private static string QualifyVariableName(string name, string iniNamespace)
    {
        string normalized = NormalizeVariableName(name);
        if (normalized.StartsWith("$\\", StringComparison.Ordinal))
        {
            return normalized;
        }

        return $"$\\{iniNamespace}\\{normalized[1..]}";
    }

    private static string NormalizeVariableName(string name)
    {
        string normalized = name.Trim().Replace('/', '\\');
        if (!ValidVariableNamePattern.IsMatch(normalized))
        {
            throw new InvalidDataException($"Invalid 3DMigoto variable name: {name}");
        }

        return normalized.ToLowerInvariant();
    }

    private static string NormalizeNamespace(string value)
    {
        string normalized = value.Trim().Trim('"').Replace('/', '\\').Trim('\\');
        if (normalized.Length == 0
            || normalized.Contains("..", StringComparison.Ordinal)
            || normalized.Contains('=')
            || normalized.Any(char.IsControl))
        {
            throw new InvalidDataException($"Invalid 3DMigoto namespace: {value}");
        }

        return normalized.ToLowerInvariant();
    }

    private static bool IsSupportedNumericValue(string value)
    {
        return NumericValuePattern.IsMatch(value)
            && double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out double parsed)
            && double.IsFinite(parsed);
    }

    private static bool TryReadSection(string line, out string section)
    {
        Match match = SectionPattern.Match(line);
        section = match.Success ? match.Groups["section"].Value.Trim() : string.Empty;
        return match.Success;
    }

    private static IEnumerable<string> EnumerateLines(string content)
    {
        using var reader = new StringReader(content);
        while (reader.ReadLine() is string line)
        {
            yield return line;
        }
    }

}
