<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <Import Project="..\Tests\TestDependencies.props" />

  <ItemGroup>
    <ProjectReference Include="..\IntegratedModManager.UpdateAgent.Core\IntegratedModManager.UpdateAgent.Core.csproj" />
  </ItemGroup>
</Project>
