<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Project="..\Tests\TestDependencies.props" />

  <ItemGroup>
    <ProjectReference Include="..\IntegratedModManager.Data\IntegratedModManager.Data.csproj" />
  </ItemGroup>
</Project>
